In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Scikit-learn version:", sklearn.__version__)

NumPy version: 2.5.2
Pandas version: 3.0.5
Scikit-learn version: 1.9.0

In [ ]:
df = pd.read_csv('ipl_matches_data_cleaned.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1212 non-null   int64
 1   season           1212 non-null   str
 2   match_number     1142 non-null   float64
 3   match_date       1212 non-null   str
 4   city             1161 non-null   str
 5   venue            1212 non-null   str
 6   team1            1212 non-null   str
 7   team2            1212 non-null   str
 8   toss_winner      1212 non-null   str
 9   toss_decision    1212 non-null   str
 10  result           1212 non-null   str
 11  match_winner     1212 non-null   str
 12  win_by_runs      546 non-null    float64
 13  win_by_wickets   641 non-null    float64
 14  player_of_match  1203 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 142.2 KB

In [ ]:
df.head(30)

,match_id,season,match_number,match_date,city,venue,team1,team2,toss_winner,toss_decision,result,match_winner,win_by_runs,win_by_wickets,player_of_match
0,335982,2008,1.0,18/04/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,win,Kolkata Knight Riders,140.0,NaN,Brendon Barrie McCullum
1,1082591,2017,1.0,05/04/2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,win,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh
2,1082592,2017,2.0,06/04/2017,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Mumbai Indians,Rising Pune Supergiant,field,win,Rising Pune Supergiant,NaN,7.0,Steven Peter Devereux Smith
3,1082593,2017,3.0,07/04/2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,win,Kolkata Knight Riders,NaN,10.0,Christopher Austin Lynn
4,1082594,2017,4.0,08/04/2017,Indore,Holkar Cricket Stadium,Punjab Kings,Rising Pune Supergiant,Punjab Kings,field,win,Punjab Kings,NaN,6.0,Glenn James Maxwell
5,1082595,2017,5.0,08/04/2017,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,win,Royal Challengers Bangalore,15.0,NaN,Kedar Mahadav Jadhav
6,1082596,2017,6.0,09/04/2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Gujarat Lions,Sunrisers Hyderabad,field,win,Sunrisers Hyderabad,NaN,9.0,Rashid Khan Arman
7,1082597,2017,7.0,09/04/2017,Mumbai,Wankhede Stadium,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,win,Mumbai Indians,NaN,4.0,Nitish Rana
8,1082598,2017,8.0,10/04/2017,Indore,Holkar Cricket Stadium,Punjab Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,win,Punjab Kings,NaN,8.0,Axar Rajeshbhai Patel
9,1082599,2017,9.0,11/04/2017,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Delhi Capitals,Rising Pune Supergiant,field,win,Delhi Capitals,97.0,NaN,Sanju Viswanath Samson
10,1082600,2017,10.0,12/04/2017,Mumbai,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,win,Mumbai Indians,NaN,4.0,Jasprit Jasbirsingh Bumrah
11,1082601,2017,11.0,13/04/2017,Kolkata,Eden Gardens,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,field,win,Kolkata Knight Riders,NaN,8.0,Sunil Philip Narine
12,1082602,2017,12.0,14/04/2017,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,win,Mumbai Indians,NaN,4.0,Kieron Adrian Pollard
13,1082603,2017,13.0,14/04/2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Rising Pune Supergiant,Gujarat Lions,field,win,Gujarat Lions,NaN,7.0,Andrew James Tye
14,1082604,2017,14.0,15/04/2017,Kolkata,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,win,Kolkata Knight Riders,17.0,NaN,Robin Venu Uthappa
15,1082605,2017,15.0,15/04/2017,Delhi,Feroz Shah Kotla,Delhi Capitals,Punjab Kings,Delhi Capitals,bat,win,Delhi Capitals,51.0,NaN,Corey James Anderson
16,1082606,2017,16.0,16/04/2017,Mumbai,Wankhede Stadium,Mumbai Indians,Gujarat Lions,Mumbai Indians,field,win,Mumbai Indians,NaN,6.0,Nitish Rana
17,1082607,2017,17.0,16/04/2017,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rising Pune Supergiant,Royal Challengers Bangalore,field,win,Rising Pune Supergiant,27.0,NaN,Benjamin Andrew Stokes
18,1082608,2017,18.0,17/04/2017,Delhi,Feroz Shah Kotla,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,bat,win,Kolkata Knight Riders,NaN,4.0,Nathan Mitchell Coulter-Nile
19,1082609,2017,19.0,17/04/2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Punjab Kings,Punjab Kings,field,win,Sunrisers Hyderabad,5.0,NaN,Bhuvneshwar Kumar Singh
20,1082610,2017,20.0,18/04/2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Royal Challengers Bangalore,Gujarat Lions,field,win,Royal Challengers Bangalore,21.0,NaN,Christopher Henry Gayle
21,1082611,2017,21.0,19/04/2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Delhi Capitals,Sunrisers Hyderabad,bat,win,Sunrisers Hyderabad,15.0,NaN,Kane Stuart Williamson
22,1082612,2017,22.0,20/04/2017,Indore,Holkar Cricket Stadium,Punjab Kings,Mumbai Indians,Mumbai Indians,field,win,Mumbai Indians,NaN,8.0,Joseph Charles Buttler
23,1082613,2017,23.0,21/04/2017,Kolkata,Eden Gardens,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,win,Gujarat Lions,NaN,4.0,Suresh Kumar Raina
24,1082614,2017,25.0,22/04/2017,Mumbai,Wankhede Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,win,Mumbai Indians,14.0,NaN,Mitchell John McClenaghan
25,1082615,2017,24.0,22/04/2017,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Sunrisers Hyderabad,Rising Pune Supergiant,field,win,Rising Pune Supergiant,NaN,6.0,Mahendra Singh Dhoni
26,1082616,2017,26.0,23/04/2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Punjab Kings,Gujarat Lions,field,win,Punjab Kings,26.0,NaN,Hashim Mahomed Amla
27,1082617,2017,27.0,23/04/2017,Kolkata,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,win,Kolkata Knight Riders,82.0,NaN,Nathan Mitchell Coulter-Nile
28,1082618,2017,28.0,24/04/2017,Mumbai,Wankhede Stadium,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,field,win,Rising Pune Supergiant,3.0,NaN,Benjamin Andrew Stokes
29,1082620,2017,30.0,26/04/2017,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,win,Kolkata Knight Riders,NaN,7.0,Robin Venu Uthappa

In [25]:
df[df.isnull().values]

,match_id,season,match_number,match_date,city,venue,team1,team2,toss_winner,toss_decision,result,match_winner,win_by_runs,win_by_wickets,player_of_match
0,335982,2008,1.0,18/04/2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,win,Kolkata Knight Riders,140.0,NaN,Brendon Barrie McCullum
1,1082591,2017,1.0,05/04/2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,win,Sunrisers Hyderabad,35.0,NaN,Yuvraj Singh
2,1082592,2017,2.0,06/04/2017,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Mumbai Indians,Rising Pune Supergiant,field,win,Rising Pune Supergiant,NaN,7.0,Steven Peter Devereux Smith
3,1082593,2017,3.0,07/04/2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,win,Kolkata Knight Riders,NaN,10.0,Christopher Austin Lynn
4,1082594,2017,4.0,08/04/2017,Indore,Holkar Cricket Stadium,Punjab Kings,Rising Pune Supergiant,Punjab Kings,field,win,Punjab Kings,NaN,6.0,Glenn James Maxwell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,39.0,27/04/2026,Delhi,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,win,Royal Challengers Bangalore,NaN,9.0,Josh Reginald Hazlewood
1208,1529283,2026,40.0,28/04/2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Punjab Kings,Rajasthan Royals,Rajasthan Royals,field,win,Rajasthan Royals,NaN,6.0,Donovan Ferreira
1209,1529284,2026,41.0,29/04/2026,Mumbai,"Wankhede Stadium, Mumbai",Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,win,Sunrisers Hyderabad,NaN,6.0,Heinrich Klaasen
1210,1529285,2026,42.0,30/04/2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bangalore,Gujarat Titans,Gujarat Titans,field,win,Gujarat Titans,NaN,4.0,Jason Omar Holder
1211,1529286,2026,43.0,01/05/2026,Jaipur,"Sawai Mansingh Stadium, Jaipur",Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,win,Delhi Capitals,NaN,7.0,Kannaur Lokesh Rahul

In [26]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
match_id,1212.0,961685.974422,390532.810455,335982.0,548362.75,1082620.5,1304079.25,1529286.0
match_number,1142.0,31.328371,18.397497,1.0,16.00,31.0,46.00,72.0
win_by_runs,546.0,30.608059,27.010366,1.0,11.00,22.0,42.00,146.0
win_by_wickets,641.0,6.182527,1.837816,1.0,5.00,6.0,7.00,10.0

In [ ]:
#the data shows us that the average victory margin by runs is 30.6 and the average victory margin by wickets is 6.18.  
#There is a standard deviation of 27runs in the victory margins batting first 
#So 68% of the games won by thr team batting first are won between 3 and 57 runs. This is a slightly larger range than I expected.

In [28]:
pip install pandas-profiling

Collecting pandas-profiling
  Using cached pandas_profiling-3.2.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Using cached joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (1.18.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (3.0.5)
Requirement already satisfied: matplotlib>=3.2.0 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (3.11.1)
Collecting pydantic>=1.8.1 (from pandas-profiling)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: PyYAML>=5.0.0 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (6.0.3)
Requirement already satisfied: jinja2>=2.11.1 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (3.1.6)
Collecting markupsafe~=2.1.1 (from pandas-profiling)
  Using cached MarkupSafe-2.1.5.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting visions==0.7.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Using cached visions-0.7.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.16.0 in ./.venv/lib/python3.14/site-packages (from pandas-profiling) (2.5.2)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Using cached htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/akshaymanek/Documents/epqcricket/.venv/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/Users/akshaymanek/Documents/epqcricket/.venv/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/akshaymanek/Documents/epqcricket/.venv/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-build-env-qpavssr7/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-build-env-qpavssr7/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-build-env-qpavssr7/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-build-env-qpavssr7/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())  # noqa: S102 # exec is intentional here
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 4, in <module>
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-install-mdyjirk8/htmlmin_7237f93fcd194562b64db6057f326b81/htmlmin/__init__.py", line 28, in <module>
          from .main import minify, Minifier
        File "/private/var/folders/b2/mhjgs1354j705kfzvy4kq0vw0000gn/T/pip-install-mdyjirk8/htmlmin_7237f93fcd194562b64db6057f326b81/htmlmin/main.py", line 28, in <module>
          import cgi
      ModuleNotFoundError: No module named 'cgi'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'htmlmin' when getting requirements to build wheel
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pandas_profiling
from pandas_profiling import ProfileReport

ModuleNotFoundError: No module named 'pandas_profiling'

In [ ]:
profile = pandas_profiling.ProfileReport(df, title="IPL Matches Data Profiling Report", explorative=True)